version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tic-tac-toe
    ports:
      - 80:80
    volumes:
        - './src:/var/www'
  mariadb:
      image: mariadb:10.1
      ports:
          - 3306:3306
      volumes:
          - mariadb:/var/lib/mysql:delegated
          - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      env_file:
          - .env
volumes:
    mariadb: